### PR TITLE
Migrate notification service to PostgreSQL

### PR DESCRIPTION
**Pull request by Izakey**

### CODE REVIEW

**Comment by awasum** [comment]
Conflicts here.

Also work with Graham to enable Travis here.

**Comment by ebenezergraham** [comment]
> Conflicts here.
> 
> Also work with Graham to enable Travis here.

@awasum I have added the Travis configuration but the one file causes the build to fail during rat tests.

@aasaru can you help me to get the rat report on Travis to rectify the problem?

I have done the rat check on my local dev and all files have the License header but strangely Travis complains about 1 file (I think it might be a log file).

**Comment by ebenezergraham** [comment]
> > Conflicts here.
> > Also work with Graham to enable Travis here.
> 
> @awasum I have added the Travis configuration but the one file causes the build to fail during rat tests.
> 
> @aasaru can you help me to get the rat report on Travis to rectify the problem?
> 
> I have done the rat check on my local dev and all files have the License header but strangely Travis complains about 1 file (I think it might be a log file).

All is well now. I simulated the build on my personal Travis account to get the report.
Upon second thoughts. Can we add an after_failure configuration to publish logs and reports somewhere? I think it will come in handy for other developers.

**Comment by awasum** [comment]
Great point, discuss it on the mailing list and see others options. Then
maybe create an issue after that.

**Comment by awasum** [comment]
This has merge conflicts.

Pull develop into this branch to be up to date.

Pull when this PR is merged: https://github.com/apache/fineract-cn-notifications/pull/11

**Comment by Izakey** [comment]
Thanks @awasum. I observed that too and will figure it out.

**Comment by ebenezergraham** [comment]
I have resolved the conflicts in PR #17. It was  much simpler to do so.

**Comment by awasum** [comment]
Closing this now. Given #17  is now in.

**Pull request closed without merging**
