### PR TITLE
Increment 2

### PR DESCRIPTION
**Pull request by ebenezergraham**
Unit and component Tests,Rest and command 

added dependencies to shared Gradle file

Created  new group IDs for SMS and Email management

Added creation and finding operations to the client manager

Created modified Email and SMS configuration domain objects

Created SMS and Email pages to support fims operations

Created Post and Get Constants for creating and retrieving Configuration entitiies

Created Unit tests for Email and SMS confiurations objects

Created component tests to test SMS and Email services

Created Domain Object Generator to help with testing

Created Command and command handlers, created mappers and refactored repositories

Grouped the Email and SMS service inside the notification service

Created SQL scripts the repository and added sample configuration data

removed sample class and other event listeners

Delete system-analysis.mdj

Delete .travis.yml

changed active mq concurrency to 1-1 and added sanity checks in customerlistener

formatted the code to use 2 line implementation and debugged SMS and Email Repository and Entities

Added component tests

refactored test sms

testing porfolio triggers

testing unsecured email sign in

debugged tests and added address updated event

### CODE REVIEW

**Comment by ebenezergraham** [comment]
Hi @awasum I have created a new request and maintained the old commits to resolve the conflicts

**Comment by ebenezergraham** [comment]
Feedback from Myrle in the old commits https://github.com/apache/fineract-cn-notifications/pull/5#issuecomment-415014208

My responses:
@myrle-krantz @awasum @Izakey 
- [x] 1.) Comment - I have added the relevant licenses to the appropriate .java files but after running ./gradlew rat files in component-test/target/ and component-test/logs/ caused it to fail

- [x] 2.) Comment - Fixed the bug SMSConfigurationTest. Other two tests inTestEmailService and TestSMSService pass however the cause error happens when storing a config. I Markus has suggested a fix so I will remove for now so and add them when figure it out.

- [x] 3.) Comment I want to used this to allow the notification admin to enable or disable specific events. This is for future development. But I think I added it too early when it's not relevent to other code

- [x] 4.) Comment - Maintained only Self_management: To be honest I don't understant the use of permittable groups. Can you shed light on this?

- [x] 16.) This class shouldn't exist. I replaced it with SMSService.

- [x] 17.) Come to think of it. I can't explain. This is how I have been doing it since I learn't how to write sql queries. And I generated the script with MySQL bench. I will remove it and read about it proper use cases.

- [x] 11.) The test which was using this method was meant to trigger customerlistener events so that I can efficiently debug the class however, it kept failing. Can you suggest a possible approach for this?

- [x] 5, 6, 7, 8, 9, 10, 13, 14

- [ ] 12.) V2 and V3 is simply to insert gateway credentials for testing purposes. Can you please suggest a better approach to achieve this?

- [ ] 15.) This repo and entity is intended to contain message template. This is in future development. I introduced it to early i guess. I believe I can leave it there for future uses

**Comment by awasum** [comment]
@Izakey Please can you review and run this to see if you can help. I have a very busy schedule ahead.
Thanks.

**Comment by Izakey** [comment]
Okay @awasum Let me review.

**Comment by Izakey** [comment]
There was 1 failure:
1) startDevServer(org.apache.fineract.cn.dev.ServiceRunner)
java.lang.IllegalArgumentException: {"timestamp":1536333475638,"status":400,"error":"Bad Request","exception":"org.springframework.web.bind.MethodArgumentNotValidException","errors":[{"codes":["NotBlank.role.permissions[1].permittableEndpointGroupIdentifier","NotBlank.role.permissions.permittableEndpointGroupIdentifier","NotBlank.permissions[1].permittableEndpointGroupIdentifier","NotBlank.permissions.permittableEndpointGroupIdentifier","NotBlank.permittableEndpointGroupIdentifier","NotBlank.java.lang.String","NotBlank"],"arguments":[{"codes":["role.permissions[1].permittableEndpointGroupIdentifier","permissions[1].permittableEndpointGroupIdentifier"],"arguments":null,"defaultMessage":"permissions[1].permittableEndpointGroupIdentifier","code":"permissions[1].permittableEndpointGroupIdentifier"}],"defaultMessage":"may not be empty","objectName":"role","field":"permissions[1].permittableEndpointGroupIdentifier","rejectedValue":null,"bindingFailure":false,"code":"NotBlank"}],"message":"Bad Request","path":"/identity/v1/roles"}
	at org.apache.fineract.cn.api.util.AnnotatedErrorDecoder.getAlternative(AnnotatedErrorDecoder.java:72)
	at org.apache.fineract.cn.api.util.AnnotatedErrorDecoder.decode(AnnotatedErrorDecoder.java:65)
	at feign.SynchronousMethodHandler.executeAndDecode(SynchronousMethodHandler.java:138)
	at feign.SynchronousMethodHandler.invoke(SynchronousMethodHandler.java:76)
	at feign.ReflectiveFeign$FeignInvocationHandler.invoke(ReflectiveFeign.java:103)
	at com.sun.proxy.$Proxy209.createRole(Unknown Source)
	at org.apache.fineract.cn.dev.ServiceRunner.createSchedulerUserRoleAndPassword(ServiceRunner.java:528)
	at org.apache.fineract.cn.dev.ServiceRunner.provisionAppsViaSeshatForTenant(ServiceRunner.java:403)
	at org.apache.fineract.cn.dev.ServiceRunner.provisionAppsViaSeshat(ServiceRunner.java:382)
	at org.apache.fineract.cn.dev.ServiceRunner.startDevServer(ServiceRunner.java:279)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.springframework.test.context.junit4.statements.RunBeforeTestMethodCallbacks.evaluate(RunBeforeTestMethodCallbacks.java:75)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.springframework.test.context.junit4.statements.RunAfterTestMethodCallbacks.evaluate(RunAfterTestMethodCallbacks.java:86)
	at org.springframework.test.context.junit4.statements.SpringRepeat.evaluate(SpringRepeat.java:84)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:252)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:94)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61)
	at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:70)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:191)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
	at org.junit.runner.JUnitCore.runMain(JUnitCore.java:77)
	at org.junit.runner.JUnitCore.main(JUnitCore.java:36)
	at org.apache.fineract.cn.dev.DemoServer.main(DemoServer.java:30)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:58)

FAILURES!!!
Tests run: 1,  Failures: 1

@ebenezergraham I had this error upon running fineract-cn-demo-server. It may just be my bad, please kindly fix it if it emerges on your end too.

**Comment by ebenezergraham** [comment]
@Izakey my build just completed and everything looks good here.

**Comment by awasum** [comment]
@ebenezergraham What a commit message... Isaac is not able to run this, you may schedule a call and then try to see what happens on his side. Do you think we can merge this code and fix any other issue later?

**Comment by ebenezergraham** [comment]
@awasum Thanks Isaac has scheduled a call with me to review the code

**Comment by awasum** [comment]
The last commit message is just too long. I am merging this and I will properly review this later this week

**Comment by Izakey** [comment]
@ebenezergraham Given that you cloned demo-server as sudoer and ran into issues, kindly update  relevant repositories based on the call we had the other day so build doesn't break for anyone else.

**Pull request merged**
