### PR TITLE
Adding after_failure procedure to CI

### PR DESCRIPTION
**Pull request by ebenezergraham**
The build outputs compilations error hence, it will not be necessary to output every log (component-test, service or api), however, no details are given for rat failures.

This will allow developers to view the report.

### CODE REVIEW

**Comment by awasum** [comment]
@aasaru Please review..

**Comment by awasum** [comment]
Is this also ready to be merged?

**Comment by aasaru** [comment]
I reviewed the changes and I agree with them.

**Comment by awasum** [comment]
Thank you, I will merge.
@aasaru have u been able to setup ur apache account and connect it to GitHub so you can merge PRs?

**Pull request merged**
