### PR TITLE
Unit and component Tests,Rest and command updates and Bug Fixes

### PR DESCRIPTION
**Pull request by ebenezergraham**
Added dependencies to shared Gradle file
Created  new group IDs for SMS and Email management
Added creation and finding operations to the client manager
Created modified Email and SMS configuration domain objects
Created SMS and Email pages to support fims operations
Created Post and Get Constants for creating and retrieving Configuration entitiies
Created Unit tests for Email and SMS confiurations objects
Created component tests to test SMS and Email services
Created Domain Object Generator to help with testing
Created Command and command handlers, created mappers and refacted repositories
Grouped the Email and SMS service inside the notification service
Created SQL scripts the repository and added sample configuration data

### CODE REVIEW

**Comment by myrle-krantz** [comment]
Unfortunately comments in github aren't threaded, so this is going to be a large dump.  I'm going to number my comments so that you can reference the comments when responding:

1.) You need to run the rat tests.  At least three files are missing their headers, and there may be other problems.  To do this run:
./gradlew rat
2.) You need to run your tests.  SMSConfigurationTest doesn't compile.  TestEmailService doesn't pass. TestSMSService doesn't pass.  All tests should compile and run.
3.) What is the purpose of the Event domain object?
4.) You probably only need one permittable group for this service. Currently you have three.
5.) Remove IAMATeapotException.  You never return this exception from any of your HTTP methods, so you can delete that throws clause without replacement from the feign client.
6.) Good job for adding validation tests cases.  Please add one for each of your domain objects (the classes in the package org.apache.fineract.cn.notification.api.v1.domain) .  Please test all of the constraints in your domain objects, not just the identifier constraints.
7.) The constraints in your domain objects do not match the constraints in your sql.  They need to match.  For example: some of your fields in SQL are strings with length 255, but you allow strings with length 512 in through the domain object validation.
8.) Your feign client needs proper function names for the notification end point.  Currently the name is the generic "entity" from the template project.
9.) Your domain objects should all contain equals, hashcode and toString.  This makes testing and debugging easier.
10.) Your NotificationEventConstants still contains SAMPLE events from the template project.  Remove these please.
11.) TestEmailService.prepareMocks is dead code.  You can remove it.
12.) TestEmailService.retrieveEmailConfiguration is redundant.  You're checking the same functionality that shouldCreateEmailConfigurationEntity already checks.  In the same way, TestsSMSService.retrieveSMSConfiguration is also redundant.  And for the same reason migration V2, and V3 do not make sense.  This data should not be part of the production code.
13.) commands need names which reflect the action to be executed.  For example EmailConfigurationCommand should be CreateEmailConfigurationCommand.  You will eventually want to add a ChangeEmailConfigurationCommand.
14.) MigrateServiceCommand is dead code.  You already have InitializeServiceCommand, so you can delete Migrate.
15.) You forgot to remove the TemplateEntity and the TemplateRepository.
16.) ConfigurationProperties SMSSender should move the configuration reading code into a package named config.  The names of the properties need to be defined in a consistent camelback style.
17.) Why are you setting the Engine and the defaultl character set in the initialsetup sql?

I have several more points, that are not PR merge blockers.  I'll bring those to the list.

**Comment by myrle-krantz** [comment]
You need to run your tests.  SMSConfigurationTest doesn't compile.  TestEmailService doesn't pass. TestSMSService doesn't pass.  All tests should compile and run.

**Comment by myrle-krantz** [comment]
What is the purpose of the Event domain object?

**Comment by ebenezergraham** [comment]
@myrle-krantz Thanks for the feedback. I expected a long this like this :smile:. Let me get down it

**Comment by ebenezergraham** [comment]
@myrle-krantz @awasum @Izakey 
- [x] 1.) Comment - I have added the relevant licenses to the appropriate .java files but after running ./gradlew rat files in component-test/target/ and component-test/logs/ caused it to fail

- [x] 2.) Comment - Fixed the bug SMSConfigurationTest. Other two tests inTestEmailService and TestSMSService pass however the cause error happens when storing a config. I Markus has suggested a fix so I will remove for now so and add them when figure it out.

- [x] 3.) Comment I want to used this to allow the notification admin to enable or disable specific events. This is for future development. But I think I added it too early when it's not relevent to other code

- [x] 4.) Comment - Maintained only Self_management: To be honest I don't understant the use of permittable groups. Can you shed light on this?

- [x] 16.) This class shouldn't exist. I replaced it with SMSService.

- [x] 17.) Come to think of it. I can't explain. This is how I have been doing it since I learn't how to write sql queries. And I generated the script with MySQL bench. I will remove it and read about it proper use cases.

- [x] 11.) The test which was using this method was meant to trigger customerlistener events so that I can efficiently debug the class however, it kept failing. Can you suggest a possible approach for this?

- [x] 5, 6, 7, 8, 9, 10, 13, 14

- [x] 12.) V2 and V3 is simply to insert gateway credentials for testing purposes. Can you please suggest a better approach to achieve this?

- [ ] 15.) This repo and entity is intended to contain message template. This is in future development. I introduced it to early i guess. I believe I can leave it there for future uses

**Comment by awasum** [comment]
I see there seems to be conflicts here. Maybe you should close this PR and send in a new one without the conflicts.

**Comment by ebenezergraham** [comment]
Yes, the conflict is because I squashed the commits to reduce the commit noise in the old repositories and remove the remaining sample classes. I wanted to rectify my mistakes but Myrle advised against doing this. I will fork a new one and submit these changes.

**Pull request closed without merging**
